### ISSUE TITLE
求开源

### ISSUE THREAD

**Issue by Dddzihan** [jinx-USTC/GI-ReID#4]
求开源

**Comment by jinx-USTC** [comment]
有公司隐私保护问题，你加我微信，你这个188号码，我给你主要部分代码



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月11日 10:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [jinx-USTC/GI-ReID] 求开源 (Issue #4) |

求开源

**Comment by jinx-USTC** [comment]
因为当时这个工作是在公司完成，离职时由于规定没有完全带走，附件zip是早期的备份和整理，仅作参考。
